# Generated by Django 4.0 on 2022-01-26 05:33

from django.db import migrations, models
import django.db.models.deletion
import organization.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text='The descriptive name of the organization', max_length=128)),
                ('name', models.SlugField(max_length=32, unique=True)),
                ('description', models.CharField(help_text='A short text describing the organization', max_length=1024)),
                ('visibility', models.IntegerField(choices=[(1, 'Private'), (2, 'Internal'), (3, 'Public')])),
                ('icon_file', models.ImageField(upload_to=organization.models.organization_directory_path)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(verbose_name=[(1, 'Admin'), (2, 'Collaborator'), (3, 'Member')])),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
