# Generated by Django 4.0 on 2022-02-08 03:23

import distribute.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The app's name (extracted from the uploaded package).", max_length=32)),
                ('package_file', models.FileField(upload_to=distribute.models.distribute_package_path)),
                ('icon_file', models.FileField(upload_to=distribute.models.distribute_icon_path)),
                ('fingerprint', models.CharField(help_text='MD5 checksum of the package binary.', max_length=32)),
                ('version', models.CharField(help_text="The package's version.\nFor iOS: CFBundleVersion from info.plist.\nFor Android: android:versionCode from AppManifest.xml.", max_length=64)),
                ('short_version', models.CharField(help_text="The package's short version.\nFor iOS: CFBundleShortVersionString from info.plist.\nFor Android: android:versionName from AppManifest.xml.", max_length=64)),
                ('internal_build', models.IntegerField()),
                ('size', models.IntegerField(help_text="The package's size in bytes.")),
                ('min_os', models.CharField(help_text="The package's minimum required operating system.", max_length=32)),
                ('bundle_identifier', models.CharField(help_text='The identifier of the apps bundle.', max_length=64)),
                ('extra', models.JSONField()),
                ('description', models.CharField(help_text="The package's description.", max_length=1024)),
                ('commit_id', models.CharField(max_length=32)),
                ('channle', models.CharField(max_length=32)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.application')),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_id', models.IntegerField()),
                ('release_notes', models.CharField(help_text="The release's release notes.", max_length=1024)),
                ('enabled', models.BooleanField(default=False, help_text='This value determines the whether a release currently is enabled or disabled.')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.application')),
            ],
        ),
        migrations.CreateModel(
            name='Upgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_notes', models.CharField(help_text="The release's release notes.", max_length=1024)),
                ('upgrade_id', models.IntegerField()),
                ('target_version', models.CharField(max_length=32)),
                ('enabled', models.BooleanField(default=False)),
                ('mandatory', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribute.release')),
            ],
        ),
        migrations.CreateModel(
            name='StoreApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.IntegerField(choices=[(1, 'Rawlink'), (2, 'Appstore'), (3, 'Googleplay'), (4, 'Microsoftstore')])),
                ('auth_data', models.JSONField()),
                ('current_version', models.CharField(max_length=64)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.application')),
            ],
        ),
        migrations.CreateModel(
            name='ReleaseStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(1, 'Initial'), (2, 'Submitreview'), (3, 'Reviewpassed'), (4, 'Reviewrejected'), (5, 'Released')])),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribute.release')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribute.storeapp')),
            ],
        ),
        migrations.CreateModel(
            name='ReleaseDeploymentKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=32)),
                ('key', models.UUIDField(default=uuid.uuid4)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.application')),
            ],
        ),
        migrations.AddField(
            model_name='release',
            name='deployment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribute.releasedeploymentkey'),
        ),
        migrations.AddField(
            model_name='release',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribute.package'),
        ),
    ]
