# Generated by Django 4.0 on 2022-01-26 05:33

import application.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.IntegerField(choices=[(1, 'Private'), (2, 'Internal'), (3, 'Public')], null=True)),
                ('display_name', models.CharField(help_text='The descriptive name of the app', max_length=128)),
                ('name', models.SlugField(max_length=32)),
                ('icon_file', models.ImageField(upload_to=application.models.application_directory_path)),
                ('description', models.CharField(help_text='A short text describing the app', max_length=1024)),
                ('release_type', models.IntegerField(choices=[(1, 'Alpha'), (2, 'Beta'), (3, 'Enterprise'), (4, 'Production'), (5, 'Store')])),
                ('os', models.IntegerField(choices=[(1, 'Android'), (2, 'iOS'), (3, 'macOS'), (4, 'Tizen'), (5, 'tvOS'), (6, 'Windows'), (7, 'Linux')], help_text='The OS the app will be running on')),
                ('platform', models.IntegerField(choices=[(1, 'JavaKotlin'), (2, 'ObjectiveCSwift'), (3, 'UWP'), (4, 'Cordova'), (5, 'ReactNative'), (6, 'Xamarin'), (7, 'Unity'), (8, 'Electron'), (9, 'WPF'), (10, 'WinForms')], help_text='The platform of the app')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='UniversalApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text='The descriptive name of the app', max_length=128)),
                ('name', models.SlugField(max_length=32, unique=True)),
                ('icon_file', models.ImageField(upload_to=application.models.universal_app_directory_path)),
                ('description', models.CharField(help_text='A short text describing the app', max_length=1024)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('android', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Android', to='application.application')),
                ('iOS', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='iOS', to='application.application')),
                ('linux', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Linux', to='application.application')),
                ('macOS', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='macOS', to='application.application')),
                ('org', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
                ('tizen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Tizen', to='application.application')),
                ('tvOS', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tvOS', to='application.application')),
                ('windows', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Windows', to='application.application')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(verbose_name=[(1, 'Manager'), (2, 'Developer'), (3, 'Viewer')])),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
